version: '3.9'

services:
  openai_proxy:
    image: ghcr.io/siberianbearofficial/simple-openai-proxy:main
    command: "poetry run uvicorn openai_proxy.app:create_app --reload --factory --port 3000 --host 0.0.0.0"
    restart: always
    ports:
      - "8000:3000"
    env_file:
      - local.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

