services:
  openai-proxy:
    build: .
    container_name: openai-proxy
    restart: unless-stopped
    command: "poetry run uvicorn openai_proxy.app:create_app --reload --factory --port 3000"
    ports:
      - "8000:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - 
